### ISSUE TITLE
Move existing implementation over to using the Instana Python API

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit-incubator/chaostoolkit-instana#16]
Move over current code to use the Instana Python API:

https://docs.instana.io/quick_start/api/#python-rest-api-client
https://github.com/instana/python-sensor/blob/master/instana/api.py

**Comment by russmiles** [comment]
Work items likely include:

- Adding the Python API to `requirements.txt`
- Changing the documentation to use the environment variables preferred by the API
- Updating the `get_all_events_in_window` function in `probes.py`
- Deciding whether `api.py` is any longer doing any valuable work; I suspect not.
- Updating the unit tests to only test what the `probes.py` now adds to the underlying Instana Python API

**Comment by gtfisher** [comment]
### Instana REST API vs Python API

As far as I can see the instan Python client api differs from the current REST Api for extracting events. It appears to be more aligned to the deprecated api: 
[Instana deprecated api](https://docs.instana.io/quick_start/api/#deprecated-partialy-already-discontinued)

The Python API exposes these methods:

```
def events(self, window_size=300000, to=None):
        if to is None:
            to = self.ts_now()
        return self.get('/api/events/', query_args={'windowsize': window_size, 'to': to})

def event(self, event_id):
        return self.get('/api/events/%s' % event_id)
```

[Instana events API (New API early access)](https://instana.github.io/openapi/#tag/Events)

In our current implementation we make the call to

https://ccchaoslabs-ccchaoslabs.instana.io/api/events
With  params: {'from': 1554143400000, 'to': 1554237055206}


We don't specify window size

Given the fact that the Python api seems more aligned to the deprecated API should we consider leaving our implementation as is with the REST API

**Comment by Lawouach** [comment]
Agreed on the analysis and outcome :)

**Comment by gtfisher** [comment]
let's close this one then
