### ISSUE TITLE
Update extensions page on Chaos Toolkit site for this extension's drivers/control when ready

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit-incubator/chaostoolkit-instana#4]
This is the page to be updated: https://chaostoolkit.org/extensions

**Comment by mperrien** [comment]
Issue can be closed.
https://github.com/chaosiq/chaostoolkit-org/issues/1

**Comment by russmiles** [comment]
Beautiful - https://chaostoolkit.org/extensions/instana
